### PR TITLE
RED-1498: Merge tag '5.2.0' into omar/juniper.master

### PR DESCRIPTION
**Pull request by OmarIthawi**
RED-1498: cont. of #8 This is going to be the final merge to bring our fork up for Juniper but with Tahoe changes.

### TODO

 - [x] Fix or skip failed views

### CODE REVIEW

**Comment by johnbaldwin** [comment]
@OmarIthawi I see this from tox:

```
  File "/home/travis/build/appsembler/edx-organizations/organizations/models.py", line 106, in <module>
696    class UserOrganizationMapping(models.Model):
697  File "/home/travis/build/appsembler/edx-organizations/organizations/models.py", line 113, in UserOrganizationMapping
698    user = models.ForeignKey(settings.AUTH_USER_MODEL)
699TypeError: __init__() missing 1 required positional argument: 'on_delete'
```

**Comment by OmarIthawi** [comment]
Thanks @johnbaldwin. It means that this PR's not ready to get merge yet. We'll need to fix those tests.

**Review by thraxil — APPROVED** [review]

**Comment by johnbaldwin** [comment]
@OmarIthawi View tests are breaking returning '400'. Do you plan on fixing these before merging this PR or is this breaking behavior something you accept and we should just merge this in?

**Comment by OmarIthawi** [comment]
@johnbaldwin It's a low priority failure, I'm keeping the PR open though until those tests are fixed or skipped.

**Comment by OmarIthawi** [comment]
I've fixed the tests, thanks John for the reminder. I'll merge once tests passes.

**Pull request merged**
